version: '3.7'

services:

  web:
    container_name: 'dotnetcore'
    image: 'mcr.microsoft.com/dotnet/core/sdk'
    command: /bin/bash

  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      # change this for a "real" app!
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
